locale: "en-US"
title: "Manuel Jose Marte"
url: https://mjmarte.github.io

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://www.bu.edu/cbr/"
footer_text: "Center for Brain Recovery"

sass:
    style: compressed
    sass_dir: _sass

nav:
# - name: "Research"
#   link: "research"
 - name: "Curriculum Vitae"
   link: "cv.pdf"
