locale: "en-US"
title: "Manuel Jose Marte"
description: "Manuel Jose Marte – Postdoctoral Research Fellow, Johns Hopkins University"
url: https://mjmarte.github.io

markdown: kramdown
#ins_logo: "./bits-logo.png"

footer: yes
footer_url: "https://score.jhmi.edu"
footer_text: "SCORE Lab"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Curriculum Vitae"
   link: "cv.pdf"
