locale: "en-US"
title: "Manuel J. Marte"
url: https://mjmarte.github.io

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://www.bu.edu/aphasiaresearch/"
footer_text: "Aphasia Research Laboratory"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Research"
   link: "research"
 - name: "Curriculum Vitae"
   link: "cv.pdf"
 - name: "Misc."
   link: "misc"
